name: beersmith3
version: 3.0.9
summary: Beer Brewing Software
description: |
  Find out how to design world class beers at home, improve your brewing
  experience and simplify your brewing day. Make mead, wine and cider as well
  with BeerSmith. As you gain in experience, BeerSmith™ grows with you.
grade: devel
confinement: devmode
base: core18

layout:
  /usr/share/BeerSmith3:
    bind: $SNAP/usr/share/BeerSmith3
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0

parts:
  beersmith3:
    plugin: dump
    source: https://s3.amazonaws.com/beersmith-3/BeerSmith-3.0.9_amd64.deb
    after: [wxwidgets-sdk]
    stage-packages:
      - libpng16-16
      - libwebkit2gtk-4.0-37
      - libsm6

  # Launcher programs to fix problems at runtime
  launchers:
    source: local/launchers
    plugin: dump
    organize:
      '*': bin/

  # The wxWidgets SDK Stage Snaps
  # https://forum.snapcraft.io/t/the-wxwidgets-sdk-stage-snaps/10877
  wxwidgets-sdk:
    plugin: nil
    stage-snaps:
      - wxwidgets-sdk-gtk3
    stage-packages:
      # Crash dialog support
      - binutils
    filesets:
      crash-dialog-support:
        - usr/bin/*addr2line
      library-shared:
        - '**/lib/**/*.so*'
      prime:
        - $crash-dialog-support
        - $library-shared

  # desktop-gtk3:
  #   build-packages:
  #     - build-essential
  #     - libgtk-3-dev
  #   make-parameters:
  #     - FLAVOR=gtk3
  #   plugin: make
  #   source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  #   source-subdir: gtk
  #   stage-packages:
  #     - libxkbcommon0
  #     - ttf-ubuntu-font-family
  #     - dmz-cursor-theme
  #     - light-themes
  #     - adwaita-icon-theme
  #     - gnome-themes-standard
  #     - shared-mime-info
  #     - libgtk-3-0
  #     - libgdk-pixbuf2.0-0
  #     - libglib2.0-bin
  #     - libgtk-3-bin
  #     - unity-gtk3-module
  #     - libappindicator3-1
  #     - locales-all
  #     - xdg-user-dirs
  #     - ibus-gtk3
  #     - libibus-1.0-5
  #     - fcitx-frontend-gtk3

apps:
  beersmith3:
    adapter: full
    command: usr/bin/beersmith3
    command-chain:
      - bin/desktop-launch
      - bin/beersmith3-launch
