name: beersmith3
version: 3.2.7
summary: Beer Brewing Software
description: |
  Find out how to design world class beers at home, improve your brewing
  experience and simplify your brewing day. Make mead, wine and cider as well
  with BeerSmith. As you gain in experience, BeerSmith™ grows with you.
grade: devel
confinement: strict
base: core20
architectures: [amd64]

parts:
  beersmith3:
    plugin: dump
    source: https://beersmith3-2.s3.amazonaws.com/BeerSmith-3.2.7_amd64.deb
    stage-packages:
        - libwebkit2gtk-4.0-37
        - libtinfo5
        - libffi7
        - libsoup-gnome2.4-1
    stage:
        # remove beersmith3 default icons
        - -usr/share/BeerSmith3/icons

  bier-icon-pack:
    plugin: dump
    source: local/BIER_icon_pack_v1.0.1.zip
    # after: [beersmith3]
    organize:
        'icons/*': usr/share/BeerSmith3/icons/
    stage: [usr/share/BeerSmith3/icons/*]

apps:
  beersmith3:
    command: usr/bin/beersmith3
    extensions: [gnome-3-38]
    plugs:
        - network
        - cups-control
    environment:
        HOME: "$SNAP_USER_COMMON"

layout:
  /usr/share/BeerSmith3:
    bind: $SNAP/usr/share/BeerSmith3
  /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0
  /usr/lib/x86_64-linux-gnu/libgtk-3:
    bind: $SNAP/lib/x86_64-linux-gnu/libgtk-3
